# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: default
    main: ./cmd/connectctl
    binary: connectctl
    flags:
      - -tags
      - netgo release
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/90poe/connectctl/pkg/version.BuildDate={{.Date}} -X github.com/90poe/connectctl/pkg/version.GitHash={{.Commit}} -X github.com/90poe/connectctl/pkg/version.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: default
    builds:
    - default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
